### ISSUE TITLE
Connections Never Closed

### ISSUE THREAD

**Issue by andrejohansson** [weiznich/wundergraph#43]
I have noticed that I reach MAX_CONNECTIONS quite quick by just sitting at home being 1 user and querying the database.

It seems like connections doesn´t get released. This is the same project as I uploaded in #41, with the exception that I updated diesel to latest (1.4.4).

Running ``select * from pg_stat_activity;`` shows that idle connections is filling up. But I also found that one query got spammed: ``SET CLIENT_ENCODING TO 'UTF8'`` 

Any ideas of why this is happening? It´s a postgresql v12 database server on ubuntu.

![image](https://user-images.githubusercontent.com/2828428/77486529-3f6fd280-6e30-11ea-81de-6ec78fb61b59.png)

**Comment by weiznich** [comment]
As you are using a connection pool connections should not be closed as they are part of the pool. After looking in your code I would assume that only 8 connections are open at any point of time, as the pool should contain 8 connections.

> But I also found that one query got spammed: SET CLIENT_ENCODING TO 'UTF8'

That is done by diesel as part of the connection setup. 

Closed because this is certainly no wundergraph issue.  The question remains what and why those connections are opened. Not sure where I would search this issue.
