### ISSUE TITLE
build is broken

### ISSUE THREAD

**Issue by toxeus** [weiznich/wundergraph#62]
It's currently not possible to build the project using Rust 1.49. Both master and 0.1.2 are broken.

![image](https://user-images.githubusercontent.com/7702854/104339447-e1fc5d80-54f7-11eb-8158-212aeb98184e.png)

**Comment by weiznich** [comment]
As the builded worked with [1.42](https://github.com/weiznich/wundergraph/runs/741798889?check_suite_focus=true) this is a rustc issue not a wundergraph issue. Could you open an issue there and report this as stable-to-stable regression?

**Comment by toxeus** [comment]
My part is concluded with reporting the issue here. You understand this project better and hence can also better argue about the supposed regression. Fact is that this crate doesn't build with latest rust which is a pity because I wanted to give it a try. Probably other people tried and failed too but without bothering to report the issue.

**Comment by weiznich** [comment]
The point is that this is not a issue with this project, but with rust itself. They promise stability, seems like they broke that promise here. I will probably open a issue for that if I find some time, but otherwise I likely wont fix that project as I believe that's the wrong way. I'm closing this issue now as this is really not a wundergraph issue.

**Comment by weiznich** [comment]
See https://github.com/rust-lang/rust/issues/80953 for further updates
